---
title: "시계열분석 2장"
output: html_document
date: "2025-05-28"

header-includes:
  - \newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glue)
list.files("../adv_reg/functions")
dir = getwd() ; mother_dir = dirname(dir)
dataset_dir = glue(dir, "/datasets", sep = "")
```

```{r}
reg_function_dir = glue(mother_dir, "/adv_reg/functions")
source(glue(reg_function_dir, "/mult_reg.R", sep = ""), echo = F)
source(glue(reg_function_dir, "/reg_diagnostics.R", sep = ""), echo = F)
```

## 2.2 다항추세모형

### 예 2.1 선형추세모형의 적합 예제

```{r}
## Example 2.1 선형모형 적합
# install.packages("lmtest")
library(lmtest) ## library for Durbin-Watson test(dwtest)
setwd(dataset_dir)
z <- scan("population.txt")
pop = round(z/10000) ; pop = ts(pop, start = c(1960))
t <- 1:length(pop) # 시간변수 생성
t2 = t*t
m1 <- lm(pop ~ t)
dwtest(m1)
summary(m1)
```

```{r}
ts.plot(pop, fitted(m1), xlab = "year", ylab = "population", lty = 1:2,
        main = "그림 2-3 총인구와 선형모형 예측값")
legend("topleft", legend = c("pop", "fitted"), lty = 1:2)
```

```{r}
ts.plot(resid(m1), type = "o", xlab = "year", ylab = "residual",
        main = "그림 2-4 선형모형 적합 후 잔차") ; abline(h = 0)
```

```{r}
acf(resid(m1), main = "잔차의 ACF")
```

```{r}
## 2차 추세모형
m2 <- lm(pop ~ t + t2)
summary(m2)
```

```{r}
ts.plot(pop, fitted(m2), xlab = "year", ylab = "population", lty = 1:2,
        main = "그림 2-5 2차 추세모형 예측값")
legend("topleft", legend = c("pop", "fitted"), lty = 1:2)
```

```{r}
ts.plot(resid(m2), type = "o", ylab = "residual",
        main = "그림 2-6 2차 추세모형 적합 후의 잔차") ; abline(h = 0)
```

```{r}
acf(resid(m2), main = "잔차의 ACF")
```

```{r}
## 로그변환 후 2차 추세모형
lnpop <- log(pop)
m3 <- lm(lnpop ~ t + t2)
summary(m3)
```

```{r}
ts.plot(lnpop, fitted(m3), xlab = "year", ylab = "log population", lty = 1:2,
        main = "로그변환 후 2차 추세모형 예측값")
legend("topleft", legend = c("lnpop", "fitted"), lty = 1:2)
```

```{r}
ts.plot(resid(m3), type = "o", ylab = "residual",
        main = "그림 2-7 로그변환 후 2차 추세모형 적합 후의 잔차") ; abline(h = 0)
```

```{r}
acf(resid(m3), main = "잔차의 ACF")
```

```{r}
dwtest(m3)
summary(m3)
```

### 계절성분만을 갖는 경우 : 계절추세모형

```{r}
## Figure 2.8 : 주기성분을 갖는 시계열
n = 100 ; t = 1:n ; a1 = -0.8 ; a2 = 1.4 ; phi1 = pi/8 ; phi2 = 3*pi/4
first = a1 * sin(pi*t/6 + phi1) ; second = a2 * sin(pi*t/3 + phi2)
z = first + second
plot(z, type = "o", lty = 1, xlab = "time", ylab = "z",
     main = "그림 2-8 두 개의 주기성분으로 구성된 시계열")
lines(first, lty = 2, col = "blue") ; lines(second, lty = 3, col = "red")
legend("left", legend = c("series", "first", "second"), lty = 1:3)
```

```{r}
## data.frame을 이용하는 경우
fig <- data.frame(z, first, second)
ts.plot(fig, col = c("black", "blue", "red"), lty = 1:3, xlab = "time", ylab = "z",
        main = "그림 2-8 두 개의 주기성분으로 구성된 시계열")
legend("right", legend = c("series", "first", "second"), lty = 1:3)
```

```{r}
t <- seq(1, 100, 1) ; error = rnorm(100, 0, 1)
Zt = -0.8 * sin(2*pi*t/4 + pi/8) + 1.4 * sin(2*pi*2*t/4 + 3*pi/4) + error
EZt = -0.8 * sin(2*pi*t/4 + pi/8) + 1.4 * sin(2*pi*2*t/4 + 3*pi/4)
Zt_ts <- ts(Zt, start = 1, frequency = 1)
EZt_ts <- ts(EZt, start = 1, frequency = 1)

ts.plot(Zt_ts, EZt_ts, xlab = "t", ylab = "Zt", lty = 1:2, col = c("blue", "red"),
        main = "Zt & EZt 그림")
legend("topleft", legend = c("Zt", "EZt"), lty = 1:2, col = c("blue", "red"))
```

### 예 2.2 추세 성분과 계절 성분을 동시에 갖는 모형 적합 예제

```{r}
# install.packages("astsa")
library(astsa) # library for function acf2
library(lmtest) # library for Durbin-Watson test(dwtest)
setwd(dataset_dir)
z <- scan("depart.txt")
dep = ts(z, frequency = 12, start = c(1984,1))
```

```{r}
ts.plot(dep, ylab = "depart", main = "그림 2-9 백화점 매출액")
```

```{r}
lndep = log(dep) # log transformation
ts.plot(lndep, ylab = "log depart", main = "그림 2-10 로그매출액")
```

```{r}
trend = time(lndep) - 1984
y = factor(cycle(lndep)) # factor를 이용한 월별 factor 생성
reg <- lm(lndep ~ 0 + trend + y)
dwtest(reg)
summary(reg)
model.matrix(reg) # 모형 계획행렬
resid_reg = ts(resid(reg), start = c(1984, 1), frequency = 12)
```

```{r}
ts.plot(resid_reg, ylab = "residual", main = "그림 2-11 잔차") ; abline(h = 0)
```

```{r}
acf2(resid_reg, main = "잔차의 ACF & PACF")
```

## 2.3 비선형추세모형

### 예 2.3 비선형모형 S-curve의 적합 예제

```{r}
## Figure 2.12 : S-curves
b0 = 0.2 ; b1 = -12 ; t = 1:60 ; z1 = exp(b0 + b1/t)

# Gompertz
b0 = 10 ; b1 = 0.15 ; k = 1 ; z2 = k * exp(-b0 * exp(-b1 * t))

# Von
b0 = 0.95 ; b1 = 0.09 ; z3 = (1 - b0 * exp((-b1)*t))^3

# Logistic
b0 = 5 ; b1 = -0.2 ; k = 1 ; z4 = k/(1 + exp(b0 + b1*t))

# Construct data frame
z = data.frame(z1, z2, z3, z4) ; z.ts = ts(z)
ts.plot(z.ts, lty = 1:4, xlab = "t", main = "그림 2-12 S-Curves")
legend("right", legend = c("Exp", "Gompertz", "Von", "Logistic"), lty = 1:4)
```

```{r}
## Example 2.3 : 비선형모형, Cable TV 자료
library(astsa) # library for function acf2
library(glue)
catv_dir = glue(dataset_dir, "/catv.txt")
z <- scan(catv_dir)
k = 70000000 ; t = 1:length(z) ; year = t + 1969
catv = ts(z, start = c(1970)) ; lncatv = log(k/catv - 1)
```

```{r}
ts.plot(catv, xlab = "year", ylab = "catv", main = "그림 2-13 Cable TV 가입자수")
```

```{r}
ts.plot(lncatv, xlab = "year", ylab = "log catv", main = "그림 2-14 로그 Cable TV 가입자수")
```

```{r}
fit <- lm(lncatv ~ t)
summary(fit)
pred = k/(exp(fitted(fit)) + 1) # CATV 예측값
resid_fit = catv - pred # 잔차

y = data.frame(catv, pred)
fig = ts(y, start = c(1970))
```

```{r}
ts.plot(fig, xlab = "year", ylab = "catv", lty = 1:2, main = "그림 2-15 관측값과 예측값")
legend("right", legend = c("Catv", "Predict"), lty = 1:2)
```

```{r}
ts.plot(resid_fit, xlab = "time", ylab = "residual", main = "그림 2-16 잔차") ; abline(h = 0)
```

```{r}
acf2(resid_fit, main = "잔차의 ACF & PACF")
```

## 2.4 자기회귀오차모형

### 예 2.4 백화점 월별 매출액 자료의 자기회귀오차모형 적합 예제

```{r}
## Example 2.4 : 자기회귀오차모형
library(astsa) # library for function acf2
library(glue)
depart_dir = glue(dataset_dir, "/depart.txt")
dept <- scan(depart_dir)
n <- 1:length(dept)
time <- ts(n, frequency = 12, start = c(1984, 1))
dept.ts <- ts(dept, frequency = 12, start = c(1984, 1))
lndept = log(dept.ts) ; y = factor(cycle(time))

fit <- lm(lndept ~ 0 + time + y)
anova(fit) ; summary(fit)

resid.ts = ts(resid(fit), start = c(1984, 1), frequency = 12)
acf2(resid.ts, main = "Residual ACF & PACF")
```

```{r}
autoreg <- arima(residuals(fit), order = c(3, 0, 0)) # 자기회귀오차모형
summary(autoreg)
plot(resid(autoreg), main = "그림 2-17 자기회귀모형 적합 후 잔차") ; abline(h = 0)
```

## 연습문제

### 2.1

```{r}
library(lmtest)
Zt = c(52, 46, 46, 52, 50, 50, 48, 45, 41, 53) ; n = length(Zt)
xt = rep(1, n) ; t = seq(1, n, 1) ; t.ts = ts(t)

Zt_bar = mean(Zt)
Zt_hat = c(rep(Zt_bar, n))

et = Zt - Zt_hat
et.ts = ts(et) ; et.ts_df = data.frame(t.ts, et.ts)

sum_xt_et = sum(xt * et) ; sum_xt_et
sum_Zt_hat_et = sum(Zt_hat * et) ; sum_Zt_hat_et

plot(xt, et, xlab = "xt", ylab = "et", lty = 1, main = "X_t & e_t 잔차 산점도")
plot(Zt_hat, et, xlab = "Zt_hat", ylab = "et", lty = 2, main = "Z_t_hat & e_t 잔차 산점도")
plot(t, et, xlab = "t", ylab = "et", lty = 3, main = "t & e_t 잔차 산점도")
ts.plot(et.ts, xlab = "t", ylab = "et", lty = 3, main = "t & e_t 잔차 산점도", type = "o")

Zt_hat
```

```{r}
n = length(Zt) ; t_alpha = qt(0.025, n - 1, lower.tail = FALSE)
t_pred = seq(11, 15, 1) ; t_ = c(t, t_pred)
Zt_ = c(Zt, rep(Zt_bar, 5))

CI_lower = Zt_bar - t_alpha * sqrt((1/(n-1)) * (1 + 1/n) * sum((Zt - Zt_hat)^2))
CI_upper = Zt_bar + t_alpha * sqrt((1/(n-1)) * (1 + 1/n) * sum((Zt - Zt_hat)^2))

plot(t_, Zt_, xlab = "t", ylab = "pred", main = "Zt_hat & 95% CI", type = "o", ylim = c(35, 60))
segments(x0 = t_pred, y0 = CI_lower,
         x1 = t_pred, y1 = CI_upper,
         col = "blue")

print(glue(CI_lower," " , CI_upper))
```

### 2.2

```{r}
t = seq(1, 15, 1)
Zt = c(303, 298, 303, 314, 303, 314, 310, 324, 317, 326, 323, 324, 331, 330, 332)
n = length(Zt) ; sum_Zt = sum(Zt) ; sum_tZt = sum(t * Zt)

beta_0_hat = ((2*(2*n + 1))/ (n * (n - 1))) * sum_Zt - (6 / (n * (n - 1))) * sum_tZt
beta_1_hat = (12 / (n * (n^2 - 1))) * sum_tZt - (6 / (n * (n - 1))) * sum_Zt

beta_hat = c(beta_0_hat, beta_1_hat) ; x0 = c(rep(1, n)) ; X = cbind(x0, t)
Zt_hat = X %*% beta_hat
et = Zt - Zt_hat

beta_hat ; et
lm_fit = lm(Zt ~ t)
lm_fit$coefficients
lm_fit$residuals

plot(x = t, lm_fit$residuals, type = "o")
dwtest(lm_fit)
```

```{r}
x0_new = c(rep(1, 5)) ; t_new = seq(16, 20, 1) ; X_new = cbind(x0_new, t_new)
Zt_hat_new = X_new %*% lm_fit$coefficients
Zt_hat_new

SSE = t(Zt) %*% (diag(1, n) - X %*% solve(t(X) %*% X) %*% t(X)) %*% Zt
MSE = SSE/(n - 2) ; sigma2_hat = MSE
X_new[1,]
class(X_new[1, ])

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
var_hat_e_hat_nl

as.numeric(MSE) * (1 + X_new[1, ] %*% solve( t(X) %*% X ) %*% X_new[1, ])


## 예측값의 95% 신뢰구간

t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
t_ = c(t, t_new) ; Zt_ = c(Zt, Zt_hat_new)

CI_lower = c(rep(0, length(t_new))) ; CI_upper = c(rep(0, length(t_new)))
CI_length_vec = c(rep(0, length(t_new)))
for (i in 1:length(t_new)){
  sd = t_alpha * sqrt(var_hat_e_hat_nl[i,i])
  CI_lower[i] = Zt_hat_new[i] - sd ; CI_upper[i] = Zt_hat_new[i] + sd  
  CI_length_vec[i] = CI_upper[i] - CI_lower[i]
}

plot(t_, Zt_, xlab = "t", ylab = "pred", main = "Zt_hat & 95% CI", type = "o", ylim = c(290, 360))
segments(x0 = t_new, y0 = CI_lower,
         x1 = t_new, y1 = CI_upper,
         col = "blue")

print(CI_length_vec)
```



```{r}
### 깃헙에서 가져온 내용인데 ggplot 활용방식만 참고하도록 하자..
# install.packages("lubridate")
# install.packages("forecast")
library(lubridate)
library(ggplot2)
library(car)
library(forecast)

# exercise 2.2
z <- c(303,298,303,314,303,314,310,324,317,326,323,324,331,330,332)
t <- 1:15
df <- data.frame(t, z)
reg <- lm(z~t, data=df)
summary(reg)
res <- data.frame(t, reg$residuals)
colnames(res) <- c('t', 'residual')
ggplot(data=res, aes(x=t,y=residual)) + 
  geom_line() +
  geom_point()

new_t <- 1:20
new <- data.frame(t=new_t)
df <- data.frame(predict(reg, new, interval="prediction", level=0.95))
df['t'] <- new_t
df['z'] <- c(z, rep('NA', 5))
print(df)
ggplot(data=df, aes(x=t)) +
  geom_line(aes(y=fit, colour='fit')) +
  geom_line(aes(y=lwr, colour='lwr')) +
  geom_line(aes(y=upr, colour='upr')) +
  geom_line(aes(x=t,y=as.numeric(z), colour='z')) +
  geom_point(aes(y=fit, colour='fit'), shape='p') +
  geom_point(aes(y=lwr, colour='lwr'), shape='L') +
  geom_point(aes(y=upr, colour='upr'), shape='U') +
  geom_point(aes(x=t,y=as.numeric(z), colour='z'), shape=20) +
  theme(legend.position = c(0.15, 0.96), 
        legend.background=element_rect(fill="transparent"), 
        legend.title=element_blank(),
        legend.direction = "horizontal")
```
### 2.5

```{r}
library(astsa) # library for function acf2
library(glue)
ex2_5_dir = glue(dataset_dir, "/ex2_5.txt")
ex2_5 <- scan(ex2_5_dir)
n <- length(ex2_5)

plot(seq(1, 30, 1), ex2_5, type = "o")
time <- ts(n, frequency = 6, start = c(1, 1))
ex2_5.ts <- ts(ex2_5, frequency = 6, start = c(1, 1))
ts.plot(ex2_5.ts)
# lndept = log(dept.ts) ; y = factor(cycle(time))
# 
# fit <- lm(lndept ~ 0 + time + y)
# anova(fit) ; summary(fit)
# 
# resid.ts = ts(resid(fit), start = c(1984, 1), frequency = 12)
# acf2(resid.ts, main = "Residual ACF & PACF")
```


```{r}
t = seq(1, n, 1) ; one = c(rep(1, n)) ; Zt = ex2_5 ; X = cbind(one, t)
lm_fit = lm(Zt ~ t)
beta_hat_lse = lm_fit$coefficients
beta_hat_lse

Zt_hat = X %*% beta_hat_lse

et = Zt - Zt_hat

plot(t, et, type = "o")
```


```{r}
sum_Zt_t = sum(Zt/t) ; sum_Zt = sum(Zt) ; sum_t = sum(1/t)

beta_0_hat_wls = ((n+1)*sum_Zt_t - 2*sum_Zt)/ ((n+1)*sum_t - 2*n)
beta_1_hat_wls = ((2/n)*sum_t*sum_Zt - 2*sum_Zt_t)/ ((n+1)*sum_t - 2*n)

beta_hat_wls = c(beta_0_hat_wls, beta_1_hat_wls)
beta_hat_wls
Zt_hat_wls = X %*% beta_hat_wls

et_wls = Zt - Zt_hat_wls

plot(t, et_wls, type = "o")
```

```{r}
ts_df = data.frame(et, et_wls)
ts_df = ts(ts_df)

ts.plot(ts_df, xlab = "t", lty = 1:3, col = c("blue", "red"))
legend("bottomleft", lty = 1:3, col = c("blue", "red"), legend = c("et", "et_wls"))
```

### 2.6

```{r}
library(astsa) # library for function acf2
library(glue)
depart_dir = glue(dataset_dir, "/depart.txt")
depart <- scan(depart_dir)
n <- length(depart)
t = seq(1, n, 1)
depart

plot(t, depart, type = "o")
```

```{r}
one = c(rep(1, n)) ; t = seq(1, n, 1)
sint = sin(2*pi*t/12) ; cost = cos(2*pi*t/12)

X = cbind(one, t, sint, cost) ; Zt = depart
beta_hat = solve(t(X) %*% X) %*% t(X) %*% Zt
round(beta_hat, 2)
Zt_hat = X %*% beta_hat
et = Zt - Zt_hat
et.ts = ts(et)
ts.plot(et.ts, lty = 1, col = c("red"), main = "잔차 산점도")
legend("topright", lty = 1, col = c("red"), legend = c("et"))

## 로그 변환 후 적합
lnZt = log(Zt)
beta_hat_tr = solve(t(X) %*% X) %*% t(X) %*% lnZt
round(beta_hat_tr, 2)
lnZt_hat = X %*% beta_hat_tr ; Zt_hat_tr = exp(lnZt_hat)
et_tr = Zt - Zt_hat_tr
et_tr.ts = ts(et_tr)
ts.plot(et_tr.ts, lty = 2, col = c("blue"), main = "잔차 산점도")
legend("topright", lty = 2, col = c("blue"), legend = c("et_logt"))

et_df = data.frame(et, et_tr)
et_df = ts(et_df)
ts.plot(et_df, lty = 1:2, col = c("red", "blue"), main = "잔차 산점도")
legend("topright", lty = 1:2, col = c("red", "blue"), legend = c("et", "et_log"))


plot(Zt, et, col = "red", lty = 1, type = "b")
plot(Zt, et_tr, col = "blue", lty = 2, type = "b")
```

### 2.7

```{r}
## (a)
z <- scan(glue(dataset_dir, "/female.txt"))
female <- ts(z, start = c(1984, 1), frequency = 12)
n = length(female) ; t = seq(1, n, 1)

plot(female, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 여성근로자수 시각화"))

lm_fit = lm(female ~ t)
lm_fit$coefficients

MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))


ts.plot(lm_fit$residuals, ylab = "residual", main = "선형추세모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(female),       # c(1984, 1)
               frequency = frequency(female))  # 12

plot(female, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 여성근로자수와 선형추세모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Linear"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1) ; t_new_df = data.frame(t = t_new) ; h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, t)
x0_new = c(rep(1, length(t_new))) ; X_new = cbind(x0_new, t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl))

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(female),       # c(1984, 1)
               frequency = frequency(female))  # 12

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(female)
time_fc     <- time_actual[n] + (1:h)/frequency(female)

ymin <- min(female, z_hat_new, CI_lower)
ymax <- max(female, z_hat_new, CI_upper)

ts.plot(female, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="월별 여성근로자수와 선형추세모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```

```{r}
## (b)
z <- scan(glue(dataset_dir, "/build.txt"))
build <- ts(z, start = c(1984, 1), frequency = 12)
n = length(build) ; t = seq(1, n, 1)

plot(build, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 건축허가면적 시각화"))


sin_t = sin(2*pi*t/12) ; cos_t = cos(2*pi*t/12)
lm_fit = lm(build ~ t + sin_t + cos_t)
lm_fit$coefficients


MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))

# trend = time(build) - 1984
# y = factor(cycle(build)) # factor를 이용한 월별 factor 생성
# lm_fit2 = lm(build ~ 0 + trend + y)
# MSE2 = sum(lm_fit2$residuals^2) / n
# print(glue("MSE2 = {MSE2}"))


ts.plot(lm_fit$residuals, ylab = "residual", main = "선형추세모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(female),       # c(1984, 1)
               frequency = frequency(female))  # 12

plot(build, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 건축허가면적과 선형계절추세모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Linear Seasonal Trend"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1)
h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, t, sin_t, cos_t)
x0_new = c(rep(1, length(t_new))) ; sin_t_new = sin(2*pi*t_new/12)
cos_t_new = cos(2*pi*t_new/12) ; X_new = cbind(x0_new, t_new, sin_t_new, cos_t_new)
t_new_df = data.frame(t = t_new, sin_t = sin_t_new, cos_t = cos_t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl)) ;se_pred

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(build),       # c(1984, 1)
               frequency = frequency(build))  # 12

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(build)
time_fc     <- time_actual[n] + (1:h)/frequency(build)

ymin <- min(build, z_hat_new, CI_lower)
ymax <- max(build, z_hat_new, CI_upper)

ts.plot(build, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="월별 건축허가면적과 선형계절추세모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```

```{r}
## (c)
z <- scan(glue(dataset_dir, "/export.txt"))
export <- ts(z, start = c(1984, 1), frequency = 12)
n = length(export) ; t = seq(1, n, 1) ; n

plot(export, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 수출액(단위 : 억$) 시각화"))


sin_t = sin(2*pi*t/12) ; cos_t = cos(2*pi*t/12)
lm_fit = lm(export ~ t + sin_t + cos_t)
lm_fit$coefficients


MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))

ts.plot(lm_fit$residuals, ylab = "residual", main = "선형추세모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(export),       # c(1984, 1)
               frequency = frequency(export))  # 12

plot(export, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("월별 수출액(단위 : 억$)과 선형계절추세모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Linear Seasonal Trend"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1)
h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, t, sin_t, cos_t)
x0_new = c(rep(1, length(t_new))) ; sin_t_new = sin(2*pi*t_new/12)
cos_t_new = cos(2*pi*t_new/12) ; X_new = cbind(x0_new, t_new, sin_t_new, cos_t_new)
t_new_df = data.frame(t = t_new, sin_t = sin_t_new, cos_t = cos_t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl)) ;se_pred

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(export),       # c(1984, 1)
               frequency = frequency(export))  # 12

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(export)
time_fc     <- time_actual[n] + (1:h)/frequency(build)

ymin <- min(export, z_hat_new, CI_lower)
ymax <- max(export, z_hat_new, CI_upper)

ts.plot(export, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="월별 수출액(단위 : 억$)과 선형계절추세모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```

```{r}
## (d)
z <- scan(glue(dataset_dir, "/usapass.txt"))
usapass <- ts(z, start = c(1984, 1), frequency = 12)
n = length(usapass) ; t = seq(1, n, 1) ; n

plot(usapass, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("미국 월별 비행기 승객 수(단위 : 천 명) 시각화"))


sin_t = sin(2*pi*t/12) ; cos_t = cos(2*pi*t/12)
lm_fit = lm(usapass ~ t + sin_t + cos_t)
lm_fit$coefficients


MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))

ts.plot(lm_fit$residuals, ylab = "residual", main = "선형계절추세모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(usapass),       # c(1984, 1)
               frequency = frequency(usapass))  # 12

plot(usapass, ylab = "Index", xlab = "year", lty = 1, col = "black",
     main = glue("미국 월별 비행기 승객 수(단위 : 천 명)과 선형계절추세모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Linear Seasonal Trend"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1)
h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, t, sin_t, cos_t)
x0_new = c(rep(1, length(t_new))) ; sin_t_new = sin(2*pi*t_new/12)
cos_t_new = cos(2*pi*t_new/12) ; X_new = cbind(x0_new, t_new, sin_t_new, cos_t_new)
t_new_df = data.frame(t = t_new, sin_t = sin_t_new, cos_t = cos_t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl)) ;se_pred

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(usapass),       # c(1984, 1)
               frequency = frequency(usapass))  # 12

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(usapass)
time_fc     <- time_actual[n] + (1:h)/frequency(usapass)

ymin <- min(usapass, z_hat_new, CI_lower)
ymax <- max(usapass, z_hat_new, CI_upper)

ts.plot(usapass, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="미국 월별 비행기 승객 수(단위 : 천 명)과 선형계절추세모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```

### 2.8

```{r}
z <- scan(glue(dataset_dir, "/stationery.txt"))
stationery <- ts(z, start = c(1984, 1), frequency = 7)
n = length(stationery) ; t = seq(1, n, 1) ; n

plot(stationery, ylab = "Index", xlab = "week", lty = 1, col = "black",
     main = glue("일별 문구류 판매액(단위 : 천원) 시각화"))


sin_t = sin(2*pi*t/7) ; cos_t = cos(2*pi*t/7)
lm_fit = lm(stationery ~ sin_t + cos_t)
lm_fit$coefficients


MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))

ts.plot(lm_fit$residuals, ylab = "residual", main = "선형계절모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(stationery),
               frequency = frequency(stationery))

plot(stationery, ylab = "Index", xlab = "week", lty = 1, col = "black",
     main = glue("일별 문구류 판매액(단위 : 천원)과 선형계절모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Seasonal"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1)
h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, sin_t, cos_t)
x0_new = c(rep(1, length(t_new))) ; sin_t_new = sin(2*pi*t_new/12)
cos_t_new = cos(2*pi*t_new/12) ; X_new = cbind(x0_new, sin_t_new, cos_t_new)
t_new_df = data.frame(sin_t = sin_t_new, cos_t = cos_t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl)) ;se_pred

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(stationery),
               frequency = frequency(stationery))

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(stationery)
time_fc     <- time_actual[n] + (1:h)/frequency(stationery)

ymin <- min(stationery, z_hat_new, CI_lower)
ymax <- max(stationery, z_hat_new, CI_upper)

ts.plot(stationery, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="일별 문구류 판매액(단위 : 천원)과 선형계절모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```

### 2.9

```{r}
z <- scan(glue(dataset_dir, "/book.txt"))
book <- ts(z, frequency = 7)
n = length(book) ; t = seq(1, n, 1) ; n

plot(book, ylab = "Book", xlab = "Week", lty = 1, col = "black",
     main = glue("일별 베스트셀러 판매부수(단위 : 권) 시각화"))

lm_fit = lm(book ~ t)
lm_fit$coefficients


MSE = sum(lm_fit$residuals^2) / n
print(glue("MSE = {MSE}"))

ts.plot(lm_fit$residuals, ylab = "residual", main = "선형추세모형의 예측오차") ; abline(h = 0)
acf(lm_fit$residuals, main = "Residual ACF")
t.test(lm_fit$residuals, mu = 0)

z_hat_ts <- ts(lm_fit$fitted.values,
               start = start(book),
               frequency = frequency(book))

plot(book, ylab = "Index", xlab = "week", lty = 1, col = "black",
     main = glue("일별 베스트셀러 판매부수(단위 : 권)과 선형추세모형"))
lines(z_hat_ts, col = "red", lty = 2)
legend("topleft", lty = 1:2, col = c("black", "red"), c("Index", "Seasonal"))

## 예측값의 95% 신뢰구간
t_new = seq(n+1, n+12, 1)
h = length(t_new)
x0 = c(rep(1, n)) ; X = cbind(x0, t)
x0_new = c(rep(1, length(t_new))) ; X_new = cbind(x0_new, t_new)
t_new_df = data.frame(t = t_new)

var_hat_e_hat_nl = as.numeric(MSE) * (diag(1, dim(X_new)[1]) + X_new %*% solve( t(X) %*% X ) %*% t(X_new))
se_pred = sqrt(diag(var_hat_e_hat_nl)) ;se_pred

### 예측
z_hat_new = predict(lm_fit, newdata = t_new_df)
print(glue("z_hat_12 = {z_hat_new[12]}"))
z_hat_ts_new <- ts(z_hat_new,
               start = start(book),
               frequency = frequency(book))

### 95% 신뢰구간
t_alpha = qt(0.025, n - 2, lower.tail = FALSE)
CI_lower = z_hat_new - t_alpha * se_pred
CI_upper = z_hat_new + t_alpha * se_pred



# t_ = c(t, t_new) ; z_hat_ts_ = c(z_hat_ts, z_hat_ts_new) ; female_ = c(female, c(rep(NA, length(t_new))))

### 시각화
# 과거(actual) + 미래(forecast) x축
time_actual <- time(book)
time_fc     <- time_actual[n] + (1:h)/frequency(book)

ymin <- min(book, z_hat_new, CI_lower)
ymax <- max(book, z_hat_new, CI_upper)

ts.plot(book, z_hat_ts,
        xlim = c(time_actual[1], time_fc[h]),
        ylim = c(ymin, ymax),
        col = c("black","red"),
        lty = c(1,2),
        ylab="Index", xlab="Year",
        main="일별 베스트셀러 판매부수(단위 : 권)과 선형추세모형")

# point forecast
lines(time_fc, z_hat_new,
      col = "blue", lty = 1)

# prediction interval
lines(time_fc, CI_lower,
      col = "lightblue", lty = 2)
lines(time_fc, CI_upper,
      col = "lightblue", lty = 2)
band_col <- rgb(173/255, 216/255, 230/255, alpha=0.4)  # 연한 하늘색 반투명
polygon(
  x = c(time_fc, rev(time_fc)),
  y = c(CI_lower, rev(CI_upper)),
  col = band_col,
  border = NA
)

legend("topleft",
       legend = c("Actual","Fitted","Forecast","95% PI"),
       col    = c("black","red","blue","lightblue"),
       lty    = c(1,2,1,2),
       bty    = "n")
```