---
title: "시계열분석 5장"
output: html_document
date: "2025-06-12"

header-includes:
  - \newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glue)
list.files("../adv_reg/functions")
dir = getwd() ; mother_dir = dirname(dir)
dataset_dir = glue(dir, "/datasets", sep = "")
```

```{r}
reg_function_dir = glue(mother_dir, "/adv_reg/functions")
source(glue(reg_function_dir, "/mult_reg.R", sep = ""), echo = F)
source(glue(reg_function_dir, "/reg_diagnostics.R", sep = ""), echo = F)

tsa_function_dir = glue(mother_dir, "/tsa/functions")
source(glue(tsa_function_dir, "/exp_smt.R", sep = ""), echo = F)
```

## 5.1 정상 확률과정

```{r}
## Figure 5.1 : 정상 AR(1) 과정 phi = -0.7
library(astsa) # library for function arima.sim
set.seed(139672)

z = 17 + arima.sim(n = 102, list(ar = -0.7), rand.gen = rnorm)
ts.plot(z, ylab = "z", main = "그림 5-1 정상 AR(1) 과정 : phi = -0.7" ) ; abline(h = 17)
```

## 5.2 확률과정의 예

```{r}
## Figure 5.2 : 백색잡음과정
set.seed(1236)
a = rnorm(300, 0, 1)
ts.plot(ts(a), ylab = "random", main = "그림 5-2 백색잡음과정") ; abline(h = 0)
```

```{r}
## Figure 5.3 : 절편이 없는 Random Walk
z = arima.sim(n = 300, list(order = c(0, 1, 0)), rand.gen = rnorm)
ts.plot(z, ylab = "z", main = "그림 5-3 절편이 없는 Random Walk")
```

```{r}
## Figure 5.4 : 절편이 있는 Random Walk
set.seed(1246)
z = ts(cumsum(0.2 + rnorm(300, 0, 1)))
ts.plot(z, ylab = "z", main = "그림 5-4 절편이 있는 Random Walk")
```

## 5.3 자기상관함수

### 예제 5.1 표본자기상관계수(SACF)의 의미

```{r}
## Example 5.1
set.seed(139672)
z_vec = c(rep(0, 102))
error_t_vec = rnorm(102, 0, 1)
for (i in 1:100){
  error_t = error_t_vec[i]
  if (i == 1){
    Z_t = error_t
    z_vec[i] = Z_t
  }else{
    Z_t = 0.7*z_vec[i-1] + error_t
    z_vec[i] = Z_t
  }
}
z_vec = z_vec + 17
z_ts = ts(z_vec)
ts.plot(z_ts, ylab = "z", main = "정상 AR(1) 과정 : phi = -0.7") ; abline(h = 17)

acf(z_ts, main = "z_ts : AR(1) 과정의 ACF : phi = -0.7")
dev.new() # device for graphics
lag1.plot(z_ts,2) # 그림 5-6 & 5-7
```

```{r}
library(astsa)
set.seed(139672)
z = 17 + arima.sim(n = 102, list(ar = -0.7), rand.gen = rnorm)
ts.plot(z, ylab = "z", main = "정상 AR(1) 과정 : phi = -0.7" ) ; abline(h = 17)


# 1행 2열 레이아웃
par(mfrow=c(1,2))

acf(z, main="그림 5-5 AR(1) ACF : phi=-0.7")
lag.plot(z, lags=2, main="그림 5-6 & 5-7 Lag Plot")

# 레이아웃 원래대로 돌려놓기
par(mfrow=c(1,1))
```

## 5.4 부분자기상관함수

### 예제 5.2 표본부분자기상관계수(SPACF)의 의미

```{r}
## Example 5.2
library(astsa) # library for function arima.sim
plot(arima.sim(list(order = c(0,0,1), ma = .8), n = 100), ylab = "x",
     main = (expression(MA(1) ~~~ theta == .8))) ; abline(h = 0) # 그림 5-8
z <- arima.sim(list(order = c(0,0,1), ma = .8), n = 100);
pacf(z, lag.max = 24, main = "그림 5-9 MA(1)의 PACF : theta = 0.8")

# 그림 5-10
plot(as.numeric(z - 0.467 * lag(z, - 1)), as.numeric(lag(z, -2) - 0.467* lag(z, -1)),
     xlab = "z(t) - 0.467*z(t+1)", ylab = "z(t+2) - 0.467*z(t+1)") ; abline(h = 0, v = 0)
```

## 연습문제

### 5.2

```{r}
gamma_hat_k = function(dataset, k){
  z_bar = mean(dataset) ; n = length(dataset)
  res = 0
  for (i in 1:(n-k)){
    z_t_z_bar = dataset[i] - z_bar
    z_tk_z_bar = dataset[i+k] - z_bar
    res = res + z_t_z_bar * z_tk_z_bar
  }
  res = res / n
  return(res)
}

z = c(7, 6, 5, 8, 9, 4, 5, 5, 4, 6, 7, 8, 5, 6, 5)
z_ts = ts(z)
gamma_hat_0 = gamma_hat_k(z_ts, k = 0)

SACF_1 = gamma_hat_k(z_ts, k = 1) / gamma_hat_0
SACF_2 = gamma_hat_k(z_ts, k = 2) / gamma_hat_0
SACF_3 = gamma_hat_k(z_ts, k = 3) / gamma_hat_0

durbin_levinson = function(dataset, K){
  library(glue)
  SACF = c(rep(0,K)) ; SPACF = c(rep(0, K)) ; rho_hat = c(rep(0, K))
  z_ts = ts(dataset)
  
  gamma_hat_0 = gamma_hat_k(z_ts, k = 0)
  for (i in 1:K){
    rho_hat[i] = gamma_hat_k(z_ts, k = i) / gamma_hat_0
    SACF[i] = rho_hat[i]
    print(glue("SACF_{i} = {rho_hat[i]}"))
  }
  
  phi_hat_mat = matrix(NA, nrow = K, ncol = K)
  
  for(i in 1:K){
    if(i == 1){
      phi_hat_mat[i,i] = rho_hat[i]
    } else {
      # 1) 대각성분 phi[i,i]
      num <- rho_hat[i] - sum(phi_hat_mat[i-1,1:(i-1)] * rho_hat[i - (1:(i-1))])
      denom <- 1 - sum(phi_hat_mat[i-1,1:(i-1)] * rho_hat[1:(i-1)])
      phi_hat_mat[i,i] <- num/denom

      # 2) 비대각성분 phi[i,1:(i-1)]
      phi_hat_mat[i,1:(i-1)] <- phi_hat_mat[i-1,1:(i-1)] - phi_hat_mat[i,i] * rev(phi_hat_mat[i-1,1:(i-1)])
    }
    SPACF[i] <- phi_hat_mat[i,i]
    print(glue("SPACF_{i} = {SPACF[i]}"))
  }
  # for (i in 1:K){
  #   for (j in 1:K){
  #     if ((i == 1) & (j == 1)){
  #       phi_hat_mat[i,j] = rho_hat[i]
  #       SPACF[i] = phi_hat_mat[i,j]
  #     }else if(i == j){
  #       l = 1 ; denum_sum = 0 ; denom_sum = 0
  #       while(l <= (i-1)){
  #         denum_sum = denum_sum + phi_hat_mat[(i-1), l] * rho_hat[i-l]
  #         denom_sum = denom_sum + phi_hat_mat[(i-1), l] * rho_hat[l]
  #         l = l + 1
  #       }
  #       denum = rho_hat[i] - denum_sum
  #       denom = 1 - denom_sum
  #       phi_hat_mat[i,j] = denum / denom
  #       print(phi_hat_mat)
  #     }else if(i > j){
  #       l = 1
  #       while(l <= (i-1)){
  #         phi_hat_mat[i,l] = phi_hat_mat[i-1,l] - phi_hat_mat[i,i] * phi_hat_mat[(i-1), i-l]
  #         l = l + 1
  #       }
  #       print(phi_hat_mat)
  #     }
  #   }
  #   SPACF[i] = phi_hat_mat[i,i]
  #   print(glue("SPACF_{i} = {SPACF[i]}"))
  # }
  return(list(SACF = SACF, SPACF = SPACF, phi_hat_mat = phi_hat_mat))
}

dl_res = durbin_levinson(z_ts, K = 3)
pacf_res = pacf(z_ts, lag.max = 24, main = "시계열 PACF")
```

### 5.3

```{r}
z <- scan(glue("{dataset_dir}/ex5_3.txt"))
t <- 1:length(z)
ex5_3 <- ts(z)
```

#### (a), (b)

```{r}
ts.plot(ex5_3)
```

#### (c)

```{r}
dev.new() # device for graphics
lag1.plot(ex5_3,1)
```

#### (d)

```{r}
acf(ex5_3, lag.max = 24, main = "ex5_3 ACF")
dl_ex5_3 = durbin_levinson(ex5_3, K = 10)
```

#### (e)

```{r}
dev.new() # device for graphics
lag1.plot(ex5_3,2)
```

#### (f)

```{r}
pacf(ex5_3, lag.max = 24, main = "ex5_3 PACF")
dl_ex5_3 = durbin_levinson(ex5_3, K = 10)
```