---
title: "시계열분석 6장"
output: html_document
date: "2025-06-25"

header-includes:
  - \newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glue)
list.files("../adv_reg/functions")
dir = getwd() ; mother_dir = dirname(dir)
dataset_dir = glue(dir, "/datasets", sep = "")
```

```{r}
reg_function_dir = glue(mother_dir, "/adv_reg/functions")
source(glue(reg_function_dir, "/mult_reg.R", sep = ""), echo = F)
source(glue(reg_function_dir, "/reg_diagnostics.R", sep = ""), echo = F)

tsa_function_dir = glue(mother_dir, "/tsa/functions")
source(glue(tsa_function_dir, "/exp_smt.R", sep = ""), echo = F)
source(glue(tsa_function_dir, "/acf_pacf.R", sep = ""), echo = F)
```

## 6.1 자기회귀과정

```{r}
## Figure 6.1, Figure 6.2, Figure 6.3 : AR(1) 과정의 시계열자료 그림 phi = 0.5 & -0.5
library(astsa) # library for function lag1.plot
set.seed(1234)

z = arima.sim(n = 100, model = list(order = c(1,0,0), ar = 0.5), rand.gen = rnorm)
y = arima.sim(n = 100, model = list(order = c(1,0,0), ar = -0.5), rand.gen = rnorm)

# 그림 6-1
ts.plot(z, ylab = "Z(t)", main = (expression(AR(1)~~phi==0.5))) ; abline(h = 0)

# 그림 6-2
ts.plot(y, ylab = "Z(t)", main = (expression(AR(1)~~phi==-0.5))) ; abline(h = 0)

# 그림 6-3
lag1.plot(z,1)
```

## 6.2 이동평균과정

```{r}
## Figure 6.6, Figure 6.7 : MA(1) 과정의 시계열자료 그림 \theta = 0.6 & -0.6

# MA 모수의 부호가 교재와는 반대임에 유의
set.seed(12347)
z = arima.sim(n=100, list(order = c(0,0,1), ma = -0.6), rand.gen = rnorm)
y = arima.sim(n=100, list(order = c(0,0,1), ma = 0.6), rand.gen = rnorm)

# 그림 6-6
ts.plot(z, ylab = "z", main = (expression(MA(1)~~~theta==0.6))) ; abline(h = 0)

# 그림 6-7
ts.plot(y, ylab = "y", main = (expression(MA(1)~~~theta==-0.6))) ; abline(h = 0)
```

## 연습문제

### 6.2

#### (모형1)

```{r}
set.seed(7714)
n = 100 ; phi = 0.8 ; mu = 0
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n))
for (i in 1:n){
  if (i == 1){
    Z_t[i] = phi * mu + e_t[i]
  }else{
    Z_t[i] = (phi * Z_t[i-1]) + e_t[i]
  }
}

Z_t = ts(Z_t)

## (a)
ts.plot(Z_t)

## (b)
dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형1 ACF")
pacf(Z_t, lag.max = 10, main = "모형1 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000 ; phi = 0.8 ; mu = 0
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n))
for (i in 1:n){
  if (i == 1){
    Z_t[i] = phi * mu + e_t[i]
  }else{
    Z_t[i] = (phi * Z_t[i-1]) + e_t[i]
  }
}

Z_t = ts(Z_t)

ts.plot(Z_t)

dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형1 ACF")
pacf(Z_t, lag.max = 10, main = "모형1 PACF")
```

#### (모형2)

```{r}
set.seed(7714)
n = 100 ; phi = 0.5 ; mu = 100/1.5
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n))
for (i in 1:n){
  if (i == 1){
    Z_t[i] = 100 + phi * mu + e_t[i]
  }else{
    Z_t[i] = 100 + (phi * Z_t[i-1]) + e_t[i]
  }
}

Z_t = ts(Z_t)

## (a)
ts.plot(Z_t)

## (b)
dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형2 ACF")
pacf(Z_t, lag.max = 10, main = "모형2 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000 ; phi = 0.5 ; mu = 100/1.5
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n))
for (i in 1:n){
  if (i == 1){
    Z_t[i] = 100 + phi * mu + e_t[i]
  }else{
    Z_t[i] = 100 + (phi * Z_t[i-1]) + e_t[i]
  }
}

Z_t = ts(Z_t)

ts.plot(Z_t)

dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형2 ACF")
pacf(Z_t, lag.max = 10, main = "모형2 PACF")
```

#### (모형3)

```{r}
set.seed(7714)
n = 100 ; theta = 0.7 ; mu = 0
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n)) ; e_0 = rnorm(1, 0, 1)
for (i in 1:n){
  if (i == 1){
    Z_t[i] = e_t[i] + theta * e_0
  }else{
    Z_t[i] = e_t[i] + theta * e_t[i-1]
  }
}

Z_t = ts(Z_t)

## (a)
ts.plot(Z_t)

## (b)
dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형3 ACF")
pacf(Z_t, lag.max = 10, main = "모형3 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000 ; theta = 0.7 ; mu = 0
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n)) ; e_0 = rnorm(1, 0, 1)
for (i in 1:n){
  if (i == 1){
    Z_t[i] = e_t[i] + theta * e_0
  }else{
    Z_t[i] = e_t[i] + theta * e_t[i-1]
  }
}

Z_t = ts(Z_t)

ts.plot(Z_t)

dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형3 ACF")
pacf(Z_t, lag.max = 10, main = "모형3 PACF")
```

#### (모형4)

```{r}
set.seed(7714)
n = 100 ; theta1 = -1.3 ; theta2 = 0.6 ; mu = 9.5
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n)) ; e_0 = rnorm(1, 0, 1) ; e_m1 = rnorm(1, 0, 1)
for (i in 1:n){
  if (i == 1){
    Z_t[i] = mu + e_t[i] + theta1 * e_0 + theta2 * e_m1
  }else if(i == 2){
    Z_t[i] = mu + e_t[i] + theta1 * e_t[i-1] + theta2 * e_0  
  }else{
    Z_t[i] = mu + e_t[i] + theta1 * e_t[i-1] + theta2 * e_t[i-2]
  }
}

Z_t = ts(Z_t)

## (a)
ts.plot(Z_t)

## (b)
dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형4 ACF")
pacf(Z_t, lag.max = 10, main = "모형4 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 100 ; theta1 = -1.3 ; theta2 = 0.6 ; mu = 9.5
e_t = rnorm(n, 0, 1) ; Z_t = c(rep(1.0, n)) ; e_0 = rnorm(1, 0, 1) ; e_m1 = rnorm(1, 0, 1)
for (i in 1:n){
  if (i == 1){
    Z_t[i] = mu + e_t[i] + theta1 * e_0 + theta2 * e_m1
  }else if(i == 2){
    Z_t[i] = mu + e_t[i] + theta1 * e_t[i-1] + theta2 * e_0  
  }else{
    Z_t[i] = mu + e_t[i] + theta1 * e_t[i-1] + theta2 * e_t[i-2]
  }
}
Z_t = ts(Z_t)

ts.plot(Z_t)

dl_Z_t = durbin_levinson(Z_t, K = 10)
acf(Z_t, lag.max = 10, main = "모형4 ACF")
pacf(Z_t, lag.max = 10, main = "모형4 PACF")


## arima.sim 코드
set.seed(7714)
n     <- 1000
theta <- c(-1.3, 0.6)
mu    <- 9.5

z = arima.sim(n = n, model = list(order = c(0,0,2), ma = theta), rand.gen = rnorm)
Z = mu + z

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형4 ACF")
pacf(Z, lag.max = 10, main = "모형4 PACF")
```

#### (모형5)

```{r}
set.seed(7714)
n = 100
phi = c(0.6)
theta = c(0.9)
mu = 38

z = arima.sim(n = n, model = list(order = c(1,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

## (a)
ts.plot(Z)

## (b)
dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형5 ACF")
pacf(Z, lag.max = 10, main = "모형5 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000
phi = c(0.6)
theta = c(0.9)
mu = 38

z = arima.sim(n = n, model = list(order = c(1,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

Z = ts(Z)

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형5 ACF")
pacf(Z, lag.max = 10, main = "모형5 PACF")
```

#### (모형6)

```{r}
set.seed(7714)
n = 100
phi = c(0.4, 0.3)
# theta = c(0.9)
mu = 0

z = arima.sim(n = n, model = list(order = c(2,0,0), ar = phi), rand.gen = rnorm)
Z = mu + z

## (a)
ts.plot(Z)

## (b)
dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형6 ACF")
pacf(Z, lag.max = 10, main = "모형6 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000
phi = c(0.4, 0.3)
# theta = c(0.9)
mu = 0

z = arima.sim(n = n, model = list(order = c(2,0,0), ar = phi), rand.gen = rnorm)
Z = mu + z

Z = ts(Z)

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형6 ACF")
pacf(Z, lag.max = 10, main = "모형6 PACF")
```

#### (모형7)

```{r}
set.seed(7714)
n = 100
phi = c(0.5)
theta = c(0.3)
mu = 0

z = arima.sim(n = n, model = list(order = c(1,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

## (a)
ts.plot(Z)

## (b)
dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형7 ACF")
pacf(Z, lag.max = 10, main = "모형7 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000
phi = c(0.5)
theta = c(0.3)
mu = 0

z = arima.sim(n = n, model = list(order = c(1,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

Z = ts(Z)

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형7 ACF")
pacf(Z, lag.max = 10, main = "모형7 PACF")
```

#### (모형8)

```{r}
set.seed(7714)
n = 100
phi = c(1.5, -0.7)
theta = c(-0.5)
mu = 100

z = arima.sim(n = n, model = list(order = c(2,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

## (a)
ts.plot(Z)

## (b)
dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형8 ACF")
pacf(Z, lag.max = 10, main = "모형8 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000
phi = c(1.5, -0.7)
theta = c(-0.5)
mu = 100

z = arima.sim(n = n, model = list(order = c(2,0,1), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

Z = ts(Z)

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형8 ACF")
pacf(Z, lag.max = 10, main = "모형8 PACF")
```

#### (모형9)

```{r}
set.seed(7714)
n = 100
phi = c(0.6)
theta = c(0.2, 0.5)
mu = 26

z = arima.sim(n = n, model = list(order = c(1,0,2), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

## (a)
ts.plot(Z)

## (b)
dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형9 ACF")
pacf(Z, lag.max = 10, main = "모형9 PACF")

## (c)
### 나중에

## (d)
set.seed(7714)
n = 1000
phi = c(0.6)
theta = c(0.2, 0.5)
mu = 26

z = arima.sim(n = n, model = list(order = c(1,0,2), ar = phi, ma = theta), rand.gen = rnorm)
Z = mu + z

Z = ts(Z)

ts.plot(Z)

dl_Z = durbin_levinson(Z, K = 10)
acf(Z, lag.max = 10, main = "모형9 ACF")
pacf(Z, lag.max = 10, main = "모형9 PACF")
```